### ISSUE TITLE
comment

### ISSUE THREAD

**Issue by berwin** [RetroAstro/cosmos-blog#1]
你的Github简介上的链接地址，，，貌似填错了。

**Comment by RetroAstro** [comment]
> 你的Github简介上的链接地址，，，貌似填错了。

@berwin emmm ... 不小心写错了 ... 可是离我填这个地址到更正它没有几分钟鸭 ... 这都被你发现了 😂

**Comment by berwin** [comment]
@RetroAstro 👀、一不小心就发现了🤷‍♀️
